-- E-COMMERCE ORDER SYSTEM

USE ecommerce_order_system;

SELECT 
C.CUSTOMER_ID,
C.FIRST_NAME,
C.LAST_NAME,
O.ORDER_DATE,
P.PRODUCT_NAME,
OI.QUANTITY
FROM CUSTOMERS C
JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_ITEMS OI
ON OI.ORDER_ID = O.ORDER_ID
JOIN PRODUCTS P 
ON P.PRODUCT_ID = OI.PRODUCT_ID;
